name: Trivy Security Scan

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:

jobs:
  trivy-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@0.20.0
      with:
        scan-type: 'fs'   # filesystem scan (code + dependencies)
        format: 'table'
        exit-code: '1'    # fail pipeline if vulnerabilities found
        ignore-unfixed: true
        severity: 'CRITICAL,HIGH'
